---
# Source: fleet-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-manager
  labels:
    helm.sh/chart: fleet-manager-0.1.0
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/instance: fleet-manager
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: fleet-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleet-manager
  labels:
    helm.sh/chart: fleet-manager-0.1.0
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/instance: fleet-manager
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/instance: fleet-manager
---
# Source: fleet-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-manager
  labels:
    helm.sh/chart: fleet-manager-0.1.0
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/instance: fleet-manager
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-manager
      app.kubernetes.io/instance: fleet-manager
  template:
    metadata:
      labels:
        helm.sh/chart: fleet-manager-0.1.0
        app.kubernetes.io/name: fleet-manager
        app.kubernetes.io/instance: fleet-manager
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: fleet-manager
      containers:
        - name: fleet-manager
          image: "priz/fleet-manager:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: fleet-manager/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "fleet-manager-test-connection"
  labels:
    helm.sh/chart: fleet-manager-0.1.0
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/instance: fleet-manager
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['fleet-manager:80']
  restartPolicy: Never
