services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
      POSTGRES_DB: fleet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fleet-manager:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: priz/fleet-manager:latest
    container_name: fleet-manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/fleet
      SQL_USERNAME: fleet
      SQL_PASSWORD: fleet

volumes:
  postgres_data:
