name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0, v2.3.1, etc.
permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Store your Docker Hub username as a secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fleet-manager:latest
